[package]
name = "wutag"
version = "0.2.0"
authors = ["wojciechkepka <wojtek.kepka@protonmail.com>"]
edition = "2018"

[[bin]]
name = "wutag"
path = "src/main.rs"

[dependencies]
libc = "0.2"
thiserror = "1"
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
serde_json = "1"
chrono = "0.4"
serde = { version = "1", features = ["derive"] }
walkdir = "2"
colored = "2"
globwalk = "0.8"
rand = "0.8"
