[package]
name = "wutagd"
version = "0.1.0"
edition = "2021"

[dependencies]
wutag_core = { path = "../wutag_core" }
wutag_ipc = { path = "../wutag_ipc" }

dirs = "4"
notify = "5"
interprocess = "1"
log = "0.4"
once_cell = "1"
pretty_env_logger = "0.4"
serde_cbor = "0.11"
thiserror = "1"
